// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCX6hP9qIJU4B5QS6ciLOxaKmelwaonpyw",
    authDomain: "online-shop-bd93e.firebaseapp.com",
    projectId: "online-shop-bd93e",
    storageBucket: "online-shop-bd93e.appspot.com",
    messagingSenderId: "452890349891",
    appId: "1:452890349891:web:397a3df72d516da6ac9ff6",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfbCAFW05wZ-ZK1_Cok9MznRwczwH_p_o',
    appId: '1:452890349891:android:381050b87c001b08ac9ff6',
    messagingSenderId: '452890349891',
    projectId: 'online-shop-bd93e',
    storageBucket: 'online-shop-bd93e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBCKlD62JdjTwiewkpFPD-MBsphZgUj0E',
    appId: '1:452890349891:ios:8168236f85683ac7ac9ff6',
    messagingSenderId: '452890349891',
    projectId: 'online-shop-bd93e',
    storageBucket: 'online-shop-bd93e.appspot.com',
    // iosClientId: '174457943368-7fq2ra4qbtcs4dqhq845ub6o30eede4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineShop',
  );
}
